export const white = '#fff'
export const light = '#f8f8f8'
export const lightGray = '#bbb'
export const gray = '#777'
export const charcoal = '#222'
export const dark = '#128333'
export const danger = '#c00'
export const dangerShade = 'rgba(200, 0, 0, 1)'
export const warning = '#fd8'
export const warningDark = '#421'
export const good = '#ace'
export const goodDark = '#036'
export const goodShade = 'rgba(200, 225, 250, 1)'

export const transparent = 'transparent'
export const shade = 'rgba(0, 0, 0, 0.5)'
export const whiteout = 'rgba(255, 255, 255, 0.9)'
