# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LNDR' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LNDR
  pod 'UrbanAirship-iOS-SDK', '~>9.0'
  pod 'PayPal-iOS-SDK'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/DynamicLinks', '~> 5.11.0'
  pod 'Firebase/Analytics'

  # target 'LNDR-tvOSTests' do
  #   inherit! :search_paths
    # Pods for testing
  # end

  # target 'LNDRTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

end

# target 'LNDR-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LNDR-tvOS

  # target 'LNDR-tvOSTests' do
  #   inherit! :search_paths
    # Pods for testing
  # end

# end
