# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LNDR' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks, I can tell you that you don't for LNDR
  # use_frameworks!

  # Pods for LNDR

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Analytics'

  pod 'UrbanAirship-iOS-SDK'

  pod 'PayPal-iOS-SDK'
end
